// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * JobState represents the lifecycle state of a preview job.
 * @readonly
 * @enum {string}
 */
export const JobState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    JobStateQueued: "queued",
    JobStateRunning: "running",
    JobStateSucceeded: "succeeded",
    JobStateFailed: "failed",
    JobStateCanceled: "canceled",
    JobStateTimedOut: "timedout",
};

/**
 * JobStatus reports a job's current state and progress.
 */
export class JobStatus {
    /**
     * Creates a new JobStatus instance.
     * @param {Partial<JobStatus>} [$$source = {}] - The source object to create the JobStatus.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {JobState}
             */
            this["status"] = JobState.$zero;
        }
        if (!("progress" in $$source)) {
            /**
             * 0..100
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JobStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JobStatus(/** @type {Partial<JobStatus>} */($$parsedSource));
    }
}

/**
 * PageRange describes a 1-based inclusive page range.
 */
export class PageRange {
    /**
     * Creates a new PageRange instance.
     * @param {Partial<PageRange>} [$$source = {}] - The source object to create the PageRange.
     */
    constructor($$source = {}) {
        if (!("start" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["end"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PageRange instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PageRange}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PageRange(/** @type {Partial<PageRange>} */($$parsedSource));
    }
}

/**
 * PreviewRequest describes the client's request to start a preview job.
 */
export class PreviewRequest {
    /**
     * Creates a new PreviewRequest instance.
     * @param {Partial<PreviewRequest>} [$$source = {}] - The source object to create the PreviewRequest.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("format" in $$source)) {
            /**
             * "webp", "jpeg", "auto"
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PageRange | null | undefined}
             */
            this["pageRange"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * PageOffset can be used by callers (e.g. splits) to request a page offset
             * relative to the provided PageRange. For example, PageOffset=1 requests
             * the next page after the start of the range.
             * @member
             * @type {number | undefined}
             */
            this["pageOffset"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PreviewRequest}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pageRange" in $$parsedSource) {
            $$parsedSource["pageRange"] = $$createField4_0($$parsedSource["pageRange"]);
        }
        return new PreviewRequest(/** @type {Partial<PreviewRequest>} */($$parsedSource));
    }
}

/**
 * PreviewResult contains the bytes (when available) and metadata for a finished job.
 */
export class PreviewResult {
    /**
     * Creates a new PreviewResult instance.
     * @param {Partial<PreviewResult>} [$$source = {}] - The source object to create the PreviewResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("data" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["data"] = "";
        }
        if (!("contentType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentType"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PreviewResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField1_0($$parsedSource["data"]);
        }
        return new PreviewResult(/** @type {Partial<PreviewResult>} */($$parsedSource));
    }
}

/**
 * PreviewStartResponse is the response returned when a preview job is enqueued.
 */
export class PreviewStartResponse {
    /**
     * Creates a new PreviewStartResponse instance.
     * @param {Partial<PreviewStartResponse>} [$$source = {}] - The source object to create the PreviewStartResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("jobID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["jobID"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewStartResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PreviewStartResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreviewStartResponse(/** @type {Partial<PreviewStartResponse>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = PageRange.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
