// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * New models for batch conversion
 */
export class BatchConversionRequest {
    /**
     * Creates a new BatchConversionRequest instance.
     * @param {Partial<BatchConversionRequest>} [$$source = {}] - The source object to create the BatchConversionRequest.
     */
    constructor($$source = {}) {
        if (!("inputPaths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["inputPaths"] = [];
        }
        if (!("outputDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputDir"] = "";
        }
        if (!("format" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("workers" in $$source)) {
            /**
             * Number of concurrent workers
             * @member
             * @type {number}
             */
            this["workers"] = 0;
        }
        if (!("options" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["options"] = {};
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("keepStructure" in $$source)) {
            /**
             * Whether to maintain directory structure
             * @member
             * @type {boolean}
             */
            this["keepStructure"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchConversionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatchConversionRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inputPaths" in $$parsedSource) {
            $$parsedSource["inputPaths"] = $$createField0_0($$parsedSource["inputPaths"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField4_0($$parsedSource["options"]);
        }
        return new BatchConversionRequest(/** @type {Partial<BatchConversionRequest>} */($$parsedSource));
    }
}

export class BatchConversionResult {
    /**
     * Creates a new BatchConversionResult instance.
     * @param {Partial<BatchConversionResult>} [$$source = {}] - The source object to create the BatchConversionResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("totalFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalFiles"] = 0;
        }
        if (!("successCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["successCount"] = 0;
        }
        if (!("failureCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failureCount"] = 0;
        }
        if (!("results" in $$source)) {
            /**
             * @member
             * @type {ConversionResult[]}
             */
            this["results"] = [];
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchConversionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatchConversionResult}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField5_0($$parsedSource["results"]);
        }
        return new BatchConversionResult(/** @type {Partial<BatchConversionResult>} */($$parsedSource));
    }
}

export class CancelJobResponseV1 {
    /**
     * Creates a new CancelJobResponseV1 instance.
     * @param {Partial<CancelJobResponseV1>} [$$source = {}] - The source object to create the CancelJobResponseV1.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("jobId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["jobId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {JobErrorV1 | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CancelJobResponseV1 instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CancelJobResponseV1}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField3_0($$parsedSource["error"]);
        }
        return new CancelJobResponseV1(/** @type {Partial<CancelJobResponseV1>} */($$parsedSource));
    }
}

export class ConversionRequest {
    /**
     * Creates a new ConversionRequest instance.
     * @param {Partial<ConversionRequest>} [$$source = {}] - The source object to create the ConversionRequest.
     */
    constructor($$source = {}) {
        if (!("inputPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["inputPath"] = "";
        }
        if (!("outputPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputPath"] = "";
        }
        if (!("format" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("options" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["options"] = {};
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConversionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConversionRequest}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        return new ConversionRequest(/** @type {Partial<ConversionRequest>} */($$parsedSource));
    }
}

export class ConversionResult {
    /**
     * Creates a new ConversionResult instance.
     * @param {Partial<ConversionResult>} [$$source = {}] - The source object to create the ConversionResult.
     */
    constructor($$source = {}) {
        if (!("inputPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["inputPath"] = "";
        }
        if (!("outputPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputPath"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConversionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConversionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConversionResult(/** @type {Partial<ConversionResult>} */($$parsedSource));
    }
}

export class JobErrorV1 {
    /**
     * Creates a new JobErrorV1 instance.
     * @param {Partial<JobErrorV1>} [$$source = {}] - The source object to create the JobErrorV1.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["details"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobErrorV1 instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JobErrorV1}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField2_0($$parsedSource["details"]);
        }
        return new JobErrorV1(/** @type {Partial<JobErrorV1>} */($$parsedSource));
    }
}

export class JobProgressV1 {
    /**
     * Creates a new JobProgressV1 instance.
     * @param {Partial<JobProgressV1>} [$$source = {}] - The source object to create the JobProgressV1.
     */
    constructor($$source = {}) {
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["current"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("stage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stage"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobProgressV1 instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JobProgressV1}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JobProgressV1(/** @type {Partial<JobProgressV1>} */($$parsedSource));
    }
}

export class JobRequestV1 {
    /**
     * Creates a new JobRequestV1 instance.
     * @param {Partial<JobRequestV1>} [$$source = {}] - The source object to create the JobRequestV1.
     */
    constructor($$source = {}) {
        if (!("toolId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toolId"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * single | batch
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("inputPaths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["inputPaths"] = [];
        }
        if (!("outputDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputDir"] = "";
        }
        if (!("options" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["options"] = {};
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["workers"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobRequestV1 instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JobRequestV1}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inputPaths" in $$parsedSource) {
            $$parsedSource["inputPaths"] = $$createField2_0($$parsedSource["inputPaths"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField4_0($$parsedSource["options"]);
        }
        return new JobRequestV1(/** @type {Partial<JobRequestV1>} */($$parsedSource));
    }
}

export class JobResultItemV1 {
    /**
     * Creates a new JobResultItemV1 instance.
     * @param {Partial<JobResultItemV1>} [$$source = {}] - The source object to create the JobResultItemV1.
     */
    constructor($$source = {}) {
        if (!("inputPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["inputPath"] = "";
        }
        if (!("outputPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputPath"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["outputs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["outputCount"] = undefined;
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {JobErrorV1 | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobResultItemV1 instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JobResultItemV1}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("outputs" in $$parsedSource) {
            $$parsedSource["outputs"] = $$createField2_0($$parsedSource["outputs"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField6_0($$parsedSource["error"]);
        }
        return new JobResultItemV1(/** @type {Partial<JobResultItemV1>} */($$parsedSource));
    }
}

export class JobResultV1 {
    /**
     * Creates a new JobResultV1 instance.
     * @param {Partial<JobResultV1>} [$$source = {}] - The source object to create the JobResultV1.
     */
    constructor($$source = {}) {
        if (!("jobId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["jobId"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("toolId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toolId"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("progress" in $$source)) {
            /**
             * @member
             * @type {JobProgressV1}
             */
            this["progress"] = (new JobProgressV1());
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {JobResultItemV1[]}
             */
            this["items"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {JobErrorV1 | null | undefined}
             */
            this["error"] = undefined;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startedAt"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["endedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobResultV1 instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JobResultV1}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType8;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("progress" in $$parsedSource) {
            $$parsedSource["progress"] = $$createField5_0($$parsedSource["progress"]);
        }
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField6_0($$parsedSource["items"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField7_0($$parsedSource["error"]);
        }
        return new JobResultV1(/** @type {Partial<JobResultV1>} */($$parsedSource));
    }
}

export class JobStatusResponseV1 {
    /**
     * Creates a new JobStatusResponseV1 instance.
     * @param {Partial<JobStatusResponseV1>} [$$source = {}] - The source object to create the JobStatusResponseV1.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("found" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["found"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {JobResultV1 | null | undefined}
             */
            this["result"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {JobErrorV1 | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobStatusResponseV1 instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JobStatusResponseV1}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType10;
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField3_0($$parsedSource["result"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        return new JobStatusResponseV1(/** @type {Partial<JobStatusResponseV1>} */($$parsedSource));
    }
}

export class ListToolsResponseV1 {
    /**
     * Creates a new ListToolsResponseV1 instance.
     * @param {Partial<ListToolsResponseV1>} [$$source = {}] - The source object to create the ListToolsResponseV1.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("tools" in $$source)) {
            /**
             * @member
             * @type {ToolCatalogEntryV1[]}
             */
            this["tools"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListToolsResponseV1 instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ListToolsResponseV1}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField2_0($$parsedSource["tools"]);
        }
        return new ListToolsResponseV1(/** @type {Partial<ListToolsResponseV1>} */($$parsedSource));
    }
}

export class PDFPreviewSourceResponseV1 {
    /**
     * Creates a new PDFPreviewSourceResponseV1 instance.
     * @param {Partial<PDFPreviewSourceResponseV1>} [$$source = {}] - The source object to create the PDFPreviewSourceResponseV1.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dataBase64"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mimeType"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {JobErrorV1 | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PDFPreviewSourceResponseV1 instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PDFPreviewSourceResponseV1}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        return new PDFPreviewSourceResponseV1(/** @type {Partial<PDFPreviewSourceResponseV1>} */($$parsedSource));
    }
}

export class RunJobResponseV1 {
    /**
     * Creates a new RunJobResponseV1 instance.
     * @param {Partial<RunJobResponseV1>} [$$source = {}] - The source object to create the RunJobResponseV1.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("jobId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["jobId"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {JobErrorV1 | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunJobResponseV1 instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunJobResponseV1}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        return new RunJobResponseV1(/** @type {Partial<RunJobResponseV1>} */($$parsedSource));
    }
}

export class SupportedFormat {
    /**
     * Creates a new SupportedFormat instance.
     * @param {Partial<SupportedFormat>} [$$source = {}] - The source object to create the SupportedFormat.
     */
    constructor($$source = {}) {
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("formats" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["formats"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SupportedFormat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SupportedFormat}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("formats" in $$parsedSource) {
            $$parsedSource["formats"] = $$createField1_0($$parsedSource["formats"]);
        }
        return new SupportedFormat(/** @type {Partial<SupportedFormat>} */($$parsedSource));
    }
}

export class ToolCatalogEntryV1 {
    /**
     * Creates a new ToolCatalogEntryV1 instance.
     * @param {Partial<ToolCatalogEntryV1>} [$$source = {}] - The source object to create the ToolCatalogEntryV1.
     */
    constructor($$source = {}) {
        if (!("manifest" in $$source)) {
            /**
             * @member
             * @type {ToolManifestV1}
             */
            this["manifest"] = (new ToolManifestV1());
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {ToolRuntimeStateV1}
             */
            this["state"] = (new ToolRuntimeStateV1());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCatalogEntryV1 instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolCatalogEntryV1}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType13;
        const $$createField1_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("manifest" in $$parsedSource) {
            $$parsedSource["manifest"] = $$createField0_0($$parsedSource["manifest"]);
        }
        if ("state" in $$parsedSource) {
            $$parsedSource["state"] = $$createField1_0($$parsedSource["state"]);
        }
        return new ToolCatalogEntryV1(/** @type {Partial<ToolCatalogEntryV1>} */($$parsedSource));
    }
}

export class ToolManifestV1 {
    /**
     * Creates a new ToolManifestV1 instance.
     * @param {Partial<ToolManifestV1>} [$$source = {}] - The source object to create the ToolManifestV1.
     */
    constructor($$source = {}) {
        if (!("toolId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toolId"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["domain"] = "";
        }
        if (!("capability" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["capability"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("supportsSingle" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supportsSingle"] = false;
        }
        if (!("supportsBatch" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supportsBatch"] = false;
        }
        if (!("inputExtensions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["inputExtensions"] = [];
        }
        if (!("outputExtensions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["outputExtensions"] = [];
        }
        if (!("runtimeDependencies" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["runtimeDependencies"] = [];
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolManifestV1 instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolManifestV1}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inputExtensions" in $$parsedSource) {
            $$parsedSource["inputExtensions"] = $$createField8_0($$parsedSource["inputExtensions"]);
        }
        if ("outputExtensions" in $$parsedSource) {
            $$parsedSource["outputExtensions"] = $$createField9_0($$parsedSource["outputExtensions"]);
        }
        if ("runtimeDependencies" in $$parsedSource) {
            $$parsedSource["runtimeDependencies"] = $$createField10_0($$parsedSource["runtimeDependencies"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField11_0($$parsedSource["tags"]);
        }
        return new ToolManifestV1(/** @type {Partial<ToolManifestV1>} */($$parsedSource));
    }
}

export class ToolRuntimeStateV1 {
    /**
     * Creates a new ToolRuntimeStateV1 instance.
     * @param {Partial<ToolRuntimeStateV1>} [$$source = {}] - The source object to create the ToolRuntimeStateV1.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * enabled | disabled | degraded
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reason"] = undefined;
        }
        if (!("healthy" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["healthy"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolRuntimeStateV1 instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolRuntimeStateV1}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolRuntimeStateV1(/** @type {Partial<ToolRuntimeStateV1>} */($$parsedSource));
    }
}

export class ValidateJobResponseV1 {
    /**
     * Creates a new ValidateJobResponseV1 instance.
     * @param {Partial<ValidateJobResponseV1>} [$$source = {}] - The source object to create the ValidateJobResponseV1.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("valid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["valid"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {JobErrorV1 | null | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidateJobResponseV1 instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ValidateJobResponseV1}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField3_0($$parsedSource["error"]);
        }
        return new ValidateJobResponseV1(/** @type {Partial<ValidateJobResponseV1>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = ConversionResult.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = JobErrorV1.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = JobProgressV1.createFrom;
const $$createType7 = JobResultItemV1.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = JobResultV1.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = ToolCatalogEntryV1.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = ToolManifestV1.createFrom;
const $$createType14 = ToolRuntimeStateV1.createFrom;
