// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as preview$0 from "../preview/models.js";

/**
 * @param {string} jobID
 * @returns {$CancellablePromise<models$0.CancelJobResponseV1>}
 */
export function CancelJobV1(jobID) {
    return $Call.ByID(3378080914, jobID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CancelPreview attempts to cancel a preview job.
 * @param {string} jobID
 * @returns {$CancellablePromise<preview$0.PreviewStartResponse>}
 */
export function CancelPreview(jobID) {
    return $Call.ByID(2053488540, jobID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {models$0.ImageAnnotatePreviewRequestV1} req
 * @returns {$CancellablePromise<models$0.ImageAnnotatePreviewResponseV1>}
 */
export function GetImageAnnotatePreviewV1(req) {
    return $Call.ByID(372302096, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {models$0.ImageCropPreviewRequestV1} req
 * @returns {$CancellablePromise<models$0.ImageCropPreviewResponseV1>}
 */
export function GetImageCropPreviewV1(req) {
    return $Call.ByID(4006508154, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} inputPath
 * @returns {$CancellablePromise<models$0.ImagePreviewSourceResponseV1>}
 */
export function GetImagePreviewSourceV1(inputPath) {
    return $Call.ByID(2617279209, inputPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} jobID
 * @returns {$CancellablePromise<models$0.JobStatusResponseV1>}
 */
export function GetJobStatusV1(jobID) {
    return $Call.ByID(1961277890, jobID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} inputPath
 * @returns {$CancellablePromise<models$0.PDFPreviewSourceResponseV1>}
 */
export function GetPDFPreviewSourceV1(inputPath) {
    return $Call.ByID(632882064, inputPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetPreview returns the preview bytes (if ready) for a job.
 * @param {string} jobID
 * @returns {$CancellablePromise<preview$0.PreviewResult>}
 */
export function GetPreview(jobID) {
    return $Call.ByID(1152353978, jobID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetPreviewStatus returns the job status for a preview job.
 * @param {string} jobID
 * @returns {$CancellablePromise<preview$0.JobStatus>}
 */
export function GetPreviewStatus(jobID) {
    return $Call.ByID(1885578308, jobID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.ListToolsResponseV1>}
 */
export function ListToolsV1() {
    return $Call.ByID(517184612).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function OpenDirectoryDialog() {
    return $Call.ByID(261105429);
}

/**
 * OpenFileDialog opens a native file dialog and returns the selected file path
 * @returns {$CancellablePromise<string>}
 */
export function OpenFileDialog() {
    return $Call.ByID(2246342916);
}

/**
 * OpenMultipleFilesDialog opens a native file dialog and returns multiple selected file paths
 * @returns {$CancellablePromise<string[]>}
 */
export function OpenMultipleFilesDialog() {
    return $Call.ByID(3029276213).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {models$0.JobRequestV1} req
 * @returns {$CancellablePromise<models$0.RunJobResponseV1>}
 */
export function RunJobV1(req) {
    return $Call.ByID(162380599, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SetContext() {
    return $Call.ByID(1814288085);
}

/**
 * Shutdown gracefully stops services owned by App.
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(2189478604);
}

/**
 * StartPreview enqueues a preview job and returns a job id.
 * @param {preview$0.PreviewRequest} req
 * @returns {$CancellablePromise<preview$0.PreviewStartResponse>}
 */
export function StartPreview(req) {
    return $Call.ByID(1123038030, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {models$0.JobRequestV1} req
 * @returns {$CancellablePromise<models$0.ValidateJobResponseV1>}
 */
export function ValidateJobV1(req) {
    return $Call.ByID(1505194326, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.CancelJobResponseV1.createFrom;
const $$createType1 = preview$0.PreviewStartResponse.createFrom;
const $$createType2 = models$0.ImageAnnotatePreviewResponseV1.createFrom;
const $$createType3 = models$0.ImageCropPreviewResponseV1.createFrom;
const $$createType4 = models$0.ImagePreviewSourceResponseV1.createFrom;
const $$createType5 = models$0.JobStatusResponseV1.createFrom;
const $$createType6 = models$0.PDFPreviewSourceResponseV1.createFrom;
const $$createType7 = preview$0.PreviewResult.createFrom;
const $$createType8 = preview$0.JobStatus.createFrom;
const $$createType9 = models$0.ListToolsResponseV1.createFrom;
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = models$0.RunJobResponseV1.createFrom;
const $$createType12 = models$0.ValidateJobResponseV1.createFrom;
